name: Build & Release macOS arm64

on:
  release:
    types: [published]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron app (arm64)
        run: npm run build

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: lectioo-macos-arm64
          path: dist/*.dmg

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 